# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main, 20-handle-action ]
  pull_request:
    branches: [ main ]

jobs:

  compile-run:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - command: g++-10
            os: ubuntu-latest
            install: sudo apt-get install libsfml-dev
          - command: clang++
            install: brew install sfml
            os: macos-latest
            flags: -stdlib=libstdc++
    steps:
  
      - uses: actions/checkout@v2
        with:
          submodules: recursive
  
      - name: Install
        run: ${{ matrix.install }}
        
      - name: Build
        run: |
          cmake --version
          mkdir build
          cmake -S . -B build -DCMAKE_CXX_COMPILER="${{ matrix.command }}" -DEXTRA_CXX_FLAGS="${{ matrix.flags }}"
          cmake --build build/
      - name: Run tests
        run: ctest build/
